# Docker compose file for netprobe
# https://github.com/xian55/netprobe_lite
name: netprobe

networks:
  netprobe-net:


services:
  redis:
    restart: always
    container_name: netprobe-redis
    image: "redis:latest"
    volumes:
      - ${CONFIG_PATH}/redis/:/etc/redis/
    networks:
      - netprobe-net
    dns:
      - 8.8.8.8
      - 8.8.4.4

  netprobe:
    restart: always
    container_name: netprobe-probe
    image: "${DOCKER_REGISTRY}:latest"
    environment:
      MODULE: "NETPROBE"
    networks:
      - netprobe-net
    dns:
      - 8.8.8.8
      - 8.8.4.4

  speedtest:
    restart: on-failure
    container_name: netprobe-speedtest
    image: "${DOCKER_REGISTRY}:latest"
    environment:
      MODULE: "SPEEDTEST"
    networks:
      - netprobe-net
    dns:
      - 8.8.8.8
      - 8.8.4.4

  presentation:
    restart: always
    container_name: netprobe-presentation
    image: "${DOCKER_REGISTRY}:latest"
    environment:
      MODULE: "PRESENTATION"
    networks:
      - netprobe-net
    dns:
      - 8.8.8.8
      - 8.8.4.4

  prometheus:
    restart: always
    container_name: netprobe-prometheus
    image: "prom/prometheus"
    volumes:
      - ${CONFIG_PATH}/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus # Persistent local storage for Prometheus data
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - netprobe-net
    dns:
      - 8.8.8.8
      - 8.8.4.4

  grafana:
    restart: always
    image: grafana/grafana-enterprise
    container_name: netprobe-grafana
    volumes:
      - ${CONFIG_PATH}/grafana/datasources/:/etc/grafana/provisioning/datasources/
      - ${CONFIG_PATH}/grafana/dashboards/:/etc/grafana/provisioning/dashboards/
      - ${CONFIG_PATH}/grafana/dashboards/:/var/lib/grafana/dashboards/
      - grafana_data:/var/lib/grafana
    ports:
      - '3001:3000'
    networks:
      - netprobe-net
    dns:
      - 8.8.8.8
      - 8.8.4.4

volumes:
  prometheus_data:
  grafana_data:
